# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDownloadtop2():

  def __init__(self, vids, link):
    self.vids = vids
    self.link = link

  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_downloadtop2(self):
    self.driver.get("https://streamscharts.com/clips?game=league-of-legends")
    self.driver.maximize_window()

    #N = 4

    for i in range(1, self.vids+1):
      name = ".h-full:nth-child(" + str(i) + ")> .flex-col"
      #print(name)
      self.driver.find_element(By.CSS_SELECTOR, name).click()
      WebDriverWait(self.driver, 15).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Download .MP4, 1080p")))
      self.driver.find_element(By.LINK_TEXT, "Download .MP4, 1080p").click()
      time.sleep(0.5)
      if i >= self.vids:
        time.sleep(2)
        self.driver.quit()
      else:
        self.driver.get(self.link)



a = TestDownloadtop2(15,"https://streamscharts.com/clips?game=league-of-legends")
a.setup_method()
a.test_downloadtop2()
