# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDownloadtop2():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_downloadtop2(self):
    self.driver.get("https://streamscharts.com/clips?game=league-of-legends")
    self.driver.maximize_window()



    self.driver.find_element(By.CSS_SELECTOR, ".h-full:nth-child(1) > .flex-col").click()
    WebDriverWait(self.driver, 15).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Download .MP4, 1080p")))
    self.driver.find_element(By.LINK_TEXT, "Download .MP4, 1080p").click()
    #time.sleep(3)

    self.driver.get("https://streamscharts.com/clips?game=league-of-legends")
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(2) > .flex-col").click()
    WebDriverWait(self.driver, 15).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Download .MP4, 1080p")))
    self.driver.find_element(By.LINK_TEXT, "Download .MP4, 1080p").click()
    #time.sleep(3)

    self.driver.get("https://streamscharts.com/clips?game=league-of-legends")
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(3) > .flex-col").click()
    WebDriverWait(self.driver, 15).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Download .MP4, 1080p")))
    self.driver.find_element(By.LINK_TEXT, "Download .MP4, 1080p").click()
    #time.sleep(3)

    self.driver.get("https://streamscharts.com/clips?game=league-of-legends")
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(4) > .flex-col").click()
    WebDriverWait(self.driver, 15).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Download .MP4, 1080p")))
    self.driver.find_element(By.LINK_TEXT, "Download .MP4, 1080p").click()
    #time.sleep(3)

    self.driver.get("https://streamscharts.com/clips?game=league-of-legends")
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(5) > .flex-col").click()
    WebDriverWait(self.driver, 15).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Download .MP4, 1080p")))
    self.driver.find_element(By.LINK_TEXT, "Download .MP4, 1080p").click()
    
    self.driver.get("https://streamscharts.com/clips?game=league-of-legends")
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(6) > .flex-col").click()
    WebDriverWait(self.driver, 15).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Download .MP4, 1080p")))
    self.driver.find_element(By.LINK_TEXT, "Download .MP4, 1080p").click()

    self.driver.get("https://streamscharts.com/clips?game=league-of-legends")
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(7) > .flex-col").click()
    WebDriverWait(self.driver, 15).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Download .MP4, 1080p")))
    self.driver.find_element(By.LINK_TEXT, "Download .MP4, 1080p").click()

    self.driver.get("https://streamscharts.com/clips?game=league-of-legends")
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(8) > .flex-col").click()
    WebDriverWait(self.driver, 15).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Download .MP4, 1080p")))
    self.driver.find_element(By.LINK_TEXT, "Download .MP4, 1080p").click()

    self.driver.get("https://streamscharts.com/clips?game=league-of-legends")
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(9) > .flex-col").click()
    WebDriverWait(self.driver, 15).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Download .MP4, 1080p")))
    self.driver.find_element(By.LINK_TEXT, "Download .MP4, 1080p").click()

    self.driver.get("https://streamscharts.com/clips?game=league-of-legends")
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(10) > .flex-col").click()
    WebDriverWait(self.driver, 15).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Download .MP4, 1080p")))
    self.driver.find_element(By.LINK_TEXT, "Download .MP4, 1080p").click()
    time.sleep(3)



    self.driver.close()
  
a = TestDownloadtop2()
a.setup_method()
a.test_downloadtop2()
a.teardown_method()
